name: Podcast Pipeline

on:
  schedule:
    - cron: "0 6 * * *"  # daily at 06:00 UTC; adjust as needed
  workflow_dispatch: {}

permissions:
  contents: write   # allow committing changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python -m src.main

      - name: Commit and push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data docs
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update data and site [skip ci]"
            git push
          fi